### ISSUE TITLE
IRC messages can't sent to Telegram

### ISSUE THREAD

**Issue by ustcltx** [FruitieX/teleirc#1]
How can I debug it ?

**Comment by ustcltx** [comment]
I think telegram.stdin.write doesn't work !

**Comment by tomcoleman** [comment]
same issue - any idea?

**Comment by FruitieX** [comment]
Sorry, it looks like the telegram-cli client had changed some syntax around. Try pulling the latest teleirc commits and see if it works now. I also had an issue after updating where telegram-cli would refuse to see my group chats, but deleting ~/.telegram-cli and logging in again fixed that issue.

Please make sure that you actually can send messages to Telegram groups when you manually run telegram-cli!

**Comment by tomcoleman** [comment]
just updated the js file now gives

root@ubuntu:~# node teleirc.js
module.js:340
    throw err;
          ^
Error: Cannot find module 'irc'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/teleirc.js:5:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
root@ubuntu:~#

**Comment by FruitieX** [comment]
Run `npm install`

**Comment by tomcoleman** [comment]
that gives me


root@ubuntu:~# npm install
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/root/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current
directo                               ry.

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /root/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
root@ubuntu:~# ls
ibotg-master  npm-debug.log             teleirc.js       tg
LICENSE       teleircConfig.js.example  teleirc.service
root@ubuntu:~#

**Comment by tomcoleman** [comment]
*root@ubuntu:~# apt-get install npm*
*Reading package lists... Done*
*Building dependency tree*
*Reading state information... Done*
*npm is already the newest version.*
*The following packages were automatically installed and are no longer
required:*
*  ax25-node libax25 libfile-copy-recursive-perl openbsd-inetd update-inetd*
*Use 'apt-get autoremove' to remove them.*
*0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.*
*root@ubuntu:~# npm install*
*npm ERR! install Couldn't read dependencies*
*npm ERR! package.json ENOENT, open '/root/package.json'*
*npm ERR! package.json This is most likely not a problem with npm itself.*
*npm ERR! package.json npm can't find a package.json file in your current
directory.*

*npm ERR! System Linux 3.16.0-38-generic*
*npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"*
*npm ERR! cwd /root*
*npm ERR! node -v v0.10.25*
*npm ERR! npm -v 1.4.21*
*npm ERR! path /root/package.json*
*npm ERR! code ENOPACKAGEJSON*
*npm ERR! errno 34*
*npm ERR!*
*npm ERR! Additional logging details can be found in:*
*npm ERR!     /root/npm-debug.log*
*npm ERR! not ok code 0*
*root@ubuntu:~#*

**Comment by FruitieX** [comment]
Try the command again inside the repository dir

**Comment by FruitieX** [comment]
Added this step to `README.md` as well :+1:

**Comment by tomcoleman** [comment]
Gives me :

root@ubuntu:~# ls
ibotg-master  LICENSE  npm-debug.log  teleircConfig.js.example  teleirc.js
 teleirc.service  tg
root@ubuntu:~# cd tg
root@ubuntu:~/tg# npm install
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/root/tg/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current
directory.

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/tg
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /root/tg/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/tg/npm-debug.log
npm ERR! not ok code 0
root@ubuntu:~/tg#

**Comment by FruitieX** [comment]
No no, not the `tg` repo but `teleirc`

**Comment by tomcoleman** [comment]
sorry bud

Ok loaded and bot is now back in IRC....

**Comment by FruitieX** [comment]
No worries, let's hope it works this time! Thanks for debugging :)

**Comment by tomcoleman** [comment]
i can see in unix the IRC chats now but nothign going from tg or to tg
now...

**Comment by tomcoleman** [comment]
any idea i can see the node.js reading the items in our IRC window but
nothing is getting announced from IRC > TG or from TG > IRC

root@ubuntu:~/teleirc# node teleirc.js
Connected to IRC server.
Using nickname: myTelegramBot
IRC message: PLEXBOT: hello
IRC message: PLEXBOT: hehe

**Comment by tomcoleman** [comment]
I can do a remote session on my terminal if that helps?
