### ISSUE TITLE
Show author of message when replying to IRC messages

### ISSUE THREAD

**Issue by lagleki** [FruitieX/teleirc#117]
If the name of your relay bot in Telegram is "@telercbot" and I reply in Telegram to a message relayed by the bot from IRC then on the IRC side I can only see:

```@telercbot, here is my reply to you.```

However, we should pass the name of the user whose relayed message we are quoting.

Since that quoted message can be accessed via msg.reply_to_message.text we should further extract the name of the IRC user from it and relay it back to IRC.

**Comment by FruitieX** [comment]
Hm, sure about that? Can you replicate this in the latest develop branch?

**Comment by FruitieX** [comment]
Similar to #62

**Comment by Mikaela** [comment]
I think this is fixed possibly in even released version, but at least can confirm that this works properly on develop. However https://github.com/FruitieX/teleirc/issues/93 is stil there.

```
2016-05-07 14:58:46+0300 <@Mikaela> mau
2016-05-07 14:58:54+0300 <#Kissaela> @Mikaela, mou
2016-05-07 14:59:40+0300  * @Mikaela tests
2016-05-07 14:59:46+0300 <#Kissaela> @Teleuforiabot, fails
```

*The \# is my prefix for WeeChat script parse_relayed_msg.*

![valinta_141](https://cloud.githubusercontent.com/assets/831184/15091986/8e091c50-1464-11e6-9f81-bb754cce2940.png)
