### ISSUE TITLE
optionally disable yellow highlight

### ISSUE THREAD

**Issue by lagleki** [FruitieX/teleirc#118]
In many IRC clients yellow is used for highlighting mentioned names so there should be an option to disable yellow color used here https://github.com/FruitieX/teleirc/blob/develop/src/tg/nickcolor.js#L7

**Comment by FruitieX** [comment]
You can disable it in your [config](https://github.com/FruitieX/teleirc/blob/develop/src/config.defaults.js#L48-L54)

Tip: use `--update-config` if you don't have this option in your config file yet.

**Comment by FruitieX** [comment]
https://github.com/FruitieX/teleirc/commit/4fc3871e76c34f157e0bc326f446e8702d0d1aff should fix the problem, and you should be able to remove yellow from the palette in your config now. Please close the issue if this resolves it for you.
