### ISSUE TITLE
Messages forwarded from channels don't say to be fowards

### ISSUE THREAD

**Issue by Mikaela** [FruitieX/teleirc#123]
![valinta_146](https://cloud.githubusercontent.com/assets/831184/15146953/9aebe7c2-16c6-11e6-86a1-e85ee244f442.png)

![valinta_147](https://cloud.githubusercontent.com/assets/831184/15146958/a359e332-16c6-11e6-8425-b81ffc8e5bcf.png)

I also think forwarded files, at least photos don't have the forwarded status.

**Comment by FruitieX** [comment]
Resolved by https://github.com/FruitieX/teleirc/compare/cfbb618be650...2617de07f2c8
