### ISSUE TITLE
Markdown (?) links don't work at IRC.

### ISSUE THREAD

**Issue by Mikaela** [FruitieX/teleirc#128]
![valinta_148](https://cloud.githubusercontent.com/assets/831184/15222252/6504e584-1877-11e6-8f39-f8faa5854dc7.png)

```
2016-05-12 19:23:36+0300 <#Kissaela> @kerbingamer376, ⚠⚠ Show spoiler ⚠⚠
```

I guess that the raw markdown at IRC would be the best way to implement it.

* Related: https://github.com/FruitieX/teleirc/issues/122

*PS. If you are wondering what the spoiler is, http://paste.ee/r/FRw1W :stuck_out_tongue_winking_eye:*

**Comment by FruitieX** [comment]
I wonder if we even have access to the raw markdown, must investigate...

**Comment by Mikaela** [comment]
I think at least the link should be accessible somehow if normal users can get it.

**Comment by FruitieX** [comment]
Here's what the message that we get from the Bot API contains:

```
 message_id: 160,
 from:
  { id: ...,
    first_name: 'Rasmus',
    last_name: 'Eskola',
    username: 'fruits' },
 chat:
  { id: ...,
    title: 'Fruits bot testing',
    type: 'supergroup' },
 date: 1463161509,
 forward_from: { id: ..., first_name: 'telegit', username: 'telegit_bot' },
 forward_date: 1462993053,
 text: 'Pull request #127 (Relay sender of raw commands) opened by FruitieX',
 entities:
  [ { type: 'text_link',
      offset: 0,
      length: 17,
      url: 'https://github.com/FruitieX/teleirc/pull/127' } ] }
```

So unfortunately, no raw access to the markdown. However we could e.g. append all `entities` of type `text_link` (not sure what other types are possible?)

**Comment by FruitieX** [comment]
Hmm actually, seems the entity contains the position of the link in the text (offset + length is exactly where the text `#17` ends). Maybe based on this we should try to reconstruct the original markdown like so:

```
[Pull request #127](https://github.com/FruitieX/teleirc/pull/127) (Relay sender of raw commands) opened by FruitieX
```

Opinions?
