### ISSUE TITLE
Handle editing Telegram messages somehow

### ISSUE THREAD

**Issue by Mikaela** [FruitieX/teleirc#134]
- <A href='https://telegram.org/blog/edit'>Edit Messages, New Mentions and More</A>

Since now all messages can be edited in any chat within two days and as typos are common on mobile and happen, I think TeleIRC should start handling them somehow.

Someone suggested git diff like

```
- Tyyped mesage her,
+ Typoed message here.
```

which might be the best, but spammy, so maybe handle it like multi-lined messages.

`- Tyyped mesage her, .. + Typoed message here.`

But would that be understood as what it is? It could always be explained though if anyone wonders. I think better symbols could be thought though.

**Comment by FruitieX** [comment]
Checking the Bot API docs, there doesn't seem to be anything new yet allowing us to catch edited messages. Keep in mind that the Bot API is an entirely different way of fetching Telegram messages than what normal clients are using, so the capabilities between these APIs may be out of sync.

It's also possible that this feature is just undocumented as of yet...

**Comment by Mikaela** [comment]
Confirmed with `teleirc -vv`: currently Telegram doesn't inform bots of message edits at all.

**Comment by Mikaela** [comment]
> [Forwarded from Combot / Dev progress, community hints&tips (Fedor Skuratov)]
> #api
> Telegram just updated their Bot API to 2.1. 

> Now we can add many important and useful features!

> https://core.telegram.org/bots/api#recent-changes


via https://telegram.me/comstatbot_news/84

**Comment by Tuupertunut** [comment]
This has been implemented in PR #236.

**Comment by Mikaela** [comment]
Thanks for noticing and sorry for slow response, my email is a chaos.
