### ISSUE TITLE
Hashtags break markdown conversion

### ISSUE THREAD

**Issue by FruitieX** [FruitieX/teleirc#135]

**Comment by Mikaela** [comment]
Aren't they "hashtags" without the space?

*I think I commented this at the group earlier, but I just now read email.*

**Comment by FruitieX** [comment]
Autocorrect ftw

**Comment by FruitieX** [comment]
Nevermind, they didn't break anything, there was just a warning about unsupported entity types. We can safely ignore that, and https://github.com/FruitieX/teleirc/compare/80d162a95abe...03d9e7b630f7 silences that.
