### ISSUE TITLE
Tell Telegram when kicks happen on IRC

### ISSUE THREAD

**Issue by Mikaela** [FruitieX/teleirc#141]
It would be nice if Telegram-side was told when kicks (and removes if possible) happen.

At @Antergos we often have people who forget to use pastebin or paste the content instead of the link which mostly always gets to another bot kicking the offender which again results to Telegram giving helpful links to pastebin to thin air.

Remove is "impoved" version of KICK which is PART sent by server and looks like:
- Troll has left (requested by Mikaela (remove message)).

**Comment by FruitieX** [comment]
Regular KICK events handled by #143

**Comment by Mikaela** [comment]
https://github.com/FruitieX/teleirc/commit/eb1b4652f221168321d7faa4ed2f08fe883a2c00

**Comment by FruitieX** [comment]
:+1:
