### ISSUE TITLE
Upload images to an external hosting

### ISSUE THREAD

**Issue by lagleki** [FruitieX/teleirc#142]
Consider using dropbox, Google photos or other image sharing services to display images sent from Telegram.

**Comment by Hardware-Hacks** [comment]
I use cloudinary for our bot, there is a nice npm package for this too.

**Comment by lagleki** [comment]
do u have a ready to use fork with this feature enabled?

**Comment by Mikaela** [comment]
Should be closed by https://github.com/FruitieX/teleirc/pull/165 ?

**Comment by lagleki** [comment]
> Should be closed by #165 ?

looks nice. Maybe add cloudinary support to the repo...

**Comment by Mikaela** [comment]
I am closing this because of #165. If you wish cloudinary support, could you open another issue for it?
