### ISSUE TITLE
Allow disabling the built-in HTTP server

### ISSUE THREAD

**Issue by Streetwalrus** [FruitieX/teleirc#153]
I use nginx to serve relayed media. For now I commented out the part which starts the built-in server, but that should be a config option.

**Comment by Bysmyyr** [comment]
I did that but then newer done it properly as it is security hole if external server is not configured precisely right(everything disabled).

**Comment by richrd** [comment]
This can be closed since it's implemented already, right?
https://github.com/FruitieX/teleirc/blob/master/src/config.defaults.js#L24
https://github.com/FruitieX/teleirc/blob/master/src/tg/index.js#L10

**Comment by Streetwalrus** [comment]
This config option will also stop the bot from sending a link at all.
https://github.com/FruitieX/teleirc/blob/b677f15e50e8f2c2813550499e8b488eff04f0b6/src/tg/util.js#L268-L276

**Comment by Mikaela** [comment]
I think I also wish @FruitieX to comment on this one before I start closing it or anything.

**Comment by FruitieX** [comment]
Correct! Disabling showMedia will disable the http listener all together.

**Comment by Streetwalrus** [comment]
I think you're missing the point. I've opened this issue because I want the bot to download media and generate links, without actually spawning an http server, since I'm already running one that is much more capable (nginx).
