### ISSUE TITLE
Use different telegram api

### ISSUE THREAD

**Issue by Bysmyyr** [FruitieX/teleirc#16]
I think our current api is quite limited. It is missing for example pic download. I made only short searching, found several of them. This atleast looks promising, and not too different so moving to it should be easy. https://www.npmjs.com/package/node-telegram-bot-api . I someone is not faster than I I can maybe do the job some day.

**Comment by Bysmyyr** [comment]
Any comments on this?

**Comment by FruitieX** [comment]
Funny, I actually migrated to that exact library in another Telegram bot project, we might want to do the same here. Downloading pictures / stickers would indeed be quite attractive, we could for example store them on a HTTP server and link to them on IRC. I will eventually look into this, but maybe you'll beat me to it :)

**Comment by FruitieX** [comment]
BTW if you do look into this, it might be a good idea to base your work off of the `refactor` branch. The branch changes quite a lot of code around, and is now just awaiting some testing until it's merged into master.

**Comment by Bysmyyr** [comment]
Ok, I maybe check that some time. It should not be big job, but I do not know when I have time. 

For the pictures, first version can be just pass the telegram tmp url to irc. It is valid only 1h but that is better than nothing.

**Comment by Bysmyyr** [comment]
Done
