### ISSUE TITLE
Hardly visible IRC colors

### ISSUE THREAD

**Issue by gumblex** [FruitieX/teleirc#169]
In https://github.com/FruitieX/teleirc/blob/develop/src/config.defaults.js#L58
There shouldn't be 'white', 'yellow', 'lime', 'cyan', 'silver' (light colors), especially white, as default because they have accessibility issues in some IRC clients for the visually challenged or people have bad display.

**Comment by zertrin** [comment]
See https://github.com/FruitieX/teleirc/issues/118

You can disable them in the config.

I leave the question of whether or not they should be enabled by default open.
