### ISSUE TITLE
option for not relaying topic messages

### ISSUE THREAD

**Issue by fczuardi** [FruitieX/teleirc#17]
When the bot is configured with ```config.irc_relay_all = true;``` all messages from IRC gets relayed, which is nice, but also if the bot quits and joins the network/channel it receives the channel topic and this gets forwarded to Telegram.

It would be nice to have an option to only forward user messages and not channel messages :)

screenshot:
![screen shot 2015-10-23 at 8 50 35 pm](https://cloud.githubusercontent.com/assets/7760/10706703/d96e11b0-79c7-11e5-858e-c2f258a8ee76.png)

**Comment by FruitieX** [comment]
I'll see what I can do, thanks for reporting!

**Comment by FruitieX** [comment]
There's now an option `sendTopic` in the [refactor](https://github.com/FruitieX/teleirc/tree/refactor) branch. You can either try this branch out now, or wait for the next teleirc release (version 0.3.0). I'll close this issue once the new version is out.
