### ISSUE TITLE
bot can not get double-byte character set nicknames.

### ISSUE THREAD

**Issue by dagenim** [FruitieX/teleirc#175]
sorry I can not speak english well.

irc to telegram
if 2byte nickname, bot send message without nickname.
only send english nickname.

**Comment by dagenim** [comment]
I resolve this problem with editing node-irc.

**Comment by Mikaela** [comment]
I don't understand what is the issue. What is the change that you made to node-irc?

**Comment by dagenim** [comment]
teleirc can not send double-byte character set nickname.(korean, japanese, chinese...)
ex) 안녕, あんねい, 平安
only nickname, can send chat.

edit /usr/local/lib/node_modules/teleirc/node_modules/irc/lib/parse_message.js

match = message.prefix.match(/^([_a-zA-Z0-9\~\[\]\\`^{}|-]*)(!([^@]+)@(.*))?$/);

this line change to

match = message.prefix.match(/^([_a-zA-Z0-9\~\[\]\\`^{}|-|\u0100-\ud800]*)(!([^@]+)@(.*))?$/);

and now work well.

**Comment by Mikaela** [comment]
I think this is https://github.com/martynsmith/node-irc/issues/456 and not an issue with TeleIRC so I am closing this issue here.

**Comment by LanHao0** [comment]
@dagenim thanks!!
