### ISSUE TITLE
Resend Telegram nick on IRC side if the message exceeds 512 bytes

### ISSUE THREAD

**Issue by Spydar007** [FruitieX/teleirc#186]
If a message is too long for IRC, the message is split into two or more messages. The limit on the message is 512 bytes, with two reserved for a trailing CR-LF pair, allowing for 510 bytes. 

IRC reads messages like so:
`:nick!ident@host PRIVMSG #channel :Message here`

For example:
`:TeleIRC!~teleirc@spydar007.com PRIVMSG #Spydar007 :<-Spydar007> Hello there`
If the above hostname and channel were the case, the message (starting after the second colon), would allow for 458 bytes.

It is important to remember that IRC looks for 512 *bytes*, not *characters*: 
`:TeleIRC!~teleirc@spydar007.com PRIVMSG #Spydar007 :<-Spydar007> Voilà`
The above will count as 71 bytes, and not 70, because the `à` character is two bytes. 

The bot should be changed to equate for the limit to the number of messages.

Currently, it will separate the message as any normal client does. 
However, the bot should split the message itself, and prefix the `<-nick> ` part onto the second message, for the purposes of clients with parsers, such as [WeeChat's parse_relayed_msg.pl](https://weechat.org/scripts/source/parse_relayed_msg.pl.html).

**Comment by Mikaela** [comment]
> Currently, it will separate the message as any normal client does.

Except that if älphäbets are used or UTF-8 characters, longer messages may end up losing some words entirely, so I am labeling this as a bug.

**Comment by Mikaela** [comment]
I believe that this was fixed by the switch to irc-framework. Please ask for this to be reopened if this isn't the case.

> However, the bot should split the message itself, and prefix the `<-nick>` part onto the second message, for the purposes of clients with parsers, such as WeeChat's parse_relayed_msg.pl.

Could you open a separate issue for this?

**Comment by richrd** [comment]
I seem to have this problem at least on master. I'm not sure if its this issue or something else, but when trying to test it with the following message, it didn't come through at all:
```
abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
```

**Comment by Mikaela** [comment]
```
2017-10-06 12:13:41+0300 <#@M1kaela> abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzA
2017-10-06 12:13:41+0300 <@T4> BCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
```

> Version: teleirc git-c6b04e2 (on branch: develop), npm-0.4.7

Do you see anything if you run `teleirc -vvv` ? If you do, could you open a new issue, as I think it's unrelated to this one?

*I am using parse_relayed_msgs.pl (https://github.com/FruitieX/teleirc/issues/168) for WeeChat so the first message shows the username that way instead of naming the relaybot.*

**Comment by richrd** [comment]
I'm on the master branch, because I couldn't get the develop branch to work. I tried that same test message again and I got this in IRC:
```
07:45          tg| <Wavii>
07:45          tg| abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWX
07:45          tg| rstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
```

This is what I get when running develop with `./bin/teleirc -vvv`
```
info: using config file from: /home/me/.teleirc/config.js
info: forcing log level to "silly"
node-telegram-bot-api deprecated Node.js v5.x and below will no longer be supported in the future module.js:409:26
error: channel * not found in config!
error: channel * not found in config!
error: channel * not found in config!
error: channel * not found in config!
```

**Comment by Mikaela** [comment]
Your log says nothing to me, I only know that

> error: channel * not found in config!

Is not an issue that prevents it from connecting to IRC or at least I see those on my other TeleIRC every time it connects to freenode, but everything works regardless.

**Comment by richrd** [comment]
Yeah, not sure why it hangs, but I've now got `develop` working quite nicely.

As I said there seems to be some small bug that causes the first message to only contain the telegram nickname. The actual message is sent after the nick in separate messages. This only happens for long messages.

**Comment by richrd** [comment]
Teleirc isn't sending the server password and that's why it can't connect to my network. I'll send a PR for with a fix..
