### ISSUE TITLE
Usernames with ">>>" break the way messages are forwarded to irc

### ISSUE THREAD

**Issue by l3kn** [FruitieX/teleirc#2]
With the way `handleTgLine` is implemented now 
if the username contains a ">>>"
the rest of the name is shown as part of the message.

A possible fix could be to use the `--json` flag when starting the telegram-cli
and change `handleTgLine` to parse json.

**Comment by FruitieX** [comment]
This is probably fixed in latest master now that we finally use the official bot API.
