### ISSUE TITLE
Relay Telegram media to IRC as URLs

### ISSUE THREAD

**Issue by FruitieX** [FruitieX/teleirc#20]
According to the [Telegram library](https://github.com/yagop/node-telegram-bot-api) we're using, we should now be able to [get URLs to sent files](https://github.com/yagop/node-telegram-bot-api#TelegramBot+getFileLink) or [download sent files](https://github.com/yagop/node-telegram-bot-api#telegrambotdownloadfilefileid-downloaddir--promise). We could use this to share the media files to IRC.

Ideally, the bot should download each media file that is sent to Telegram, host them via HTTP with for example [`node-static`](https://github.com/cloudhead/node-static), and then send an URL to the hosted file to IRC. We could also just send the link we get from `getFileLink()`, but it's only valid for one hour.

**Comment by Bysmyyr** [comment]
Basic version implemented #22

**Comment by Bysmyyr** [comment]
Saving pics locally go for low priority for now as looks like those api links works long enough. Now I have pic link working after 14h from getting it.

**Comment by FruitieX** [comment]
I've now implemented the local downloads and hosting of files. Mostly because the bot API token was visible in the download URLs :smile:, but now we also don't need to worry about expiring links. 

Remaining work on this issue is to implement downloading for all the different media types, so far I've got photos and stickers working.

**Comment by FruitieX** [comment]
Postponing to 0.5.0. The most important media types are covered, the rest are just nice to have.

**Comment by lagleki** [comment]
Where can I use the fix for photos and stickers only?

**Comment by Bysmyyr** [comment]
Now all media types are covered in develop branch

**Comment by FruitieX** [comment]
:+1: I think we can close this

**Comment by FruitieX** [comment]
@lagleki next hotfix release on npm is due soon, it's waiting for an updated version of the node-irc module. (fixes a serious reconnect issue)
