### ISSUE TITLE
Commands do not go through when using /command

### ISSUE THREAD

**Issue by TomokoK** [FruitieX/teleirc#204]
Using the latest commit as of 8/20/17. When executing /command x on telegram, the bot will respond as if it is executing the given command, but doesn't actually execute it on the irc side.

**Comment by TomokoK** [comment]
here's an example: [telegram](https://sr.ht/itrP.jpg) to [irc](https://sr.ht/81mQ.png)

**Comment by adedomin** [comment]
ya I'll look into it. I wasn't aware of this feature.

**Comment by adedomin** [comment]
13:48 < tg> <adedominic> /command moose --help
13:48 < tg> moose --help
13:48 < NeoMoose> usage: [.!]*moose [--latest|--random|--search|--] moosename

is that what it's supposed to look like?

**Comment by Mikaela** [comment]
#206 & https://help.github.com/articles/closing-issues-using-keywords/
