### ISSUE TITLE
identd

### ISSUE THREAD

**Issue by Cajs** [FruitieX/teleirc#205]
Hey,

Was wondering how you configure teleirc to connect to oidentd?
Couldn't see anything in the config or anything in existing issues.

Kind Regards,
Cameron

**Comment by Mikaela** [comment]
I think this isn't an issue with TeleIRC as port 113 would usually require root and IRC users generally don't touch the config files of other services, I only know ZNC to do that.

I would recommend you to run TeleIRC as a separate user or connect it to different server than your other services and then taking a look at `man oidentd.conf`.

```man

EXAMPLE $HOME/.oidentd.conf FILE
       global {
            reply "unknown"
       }

       Reply with "unknown" to all successful ident lookups.

       to irc.example.org {
            reply "example"
       }

       Reply with "example" to ident  lookups  for  connections  to  irc.exam‐
       ple.org.
```
