### ISSUE TITLE
config.ircOptions userName does nothing, SASL is broken

### ISSUE THREAD

**Issue by Mikaela** [FruitieX/teleirc#207]
The IRC username/ident always appears as `ircbot` and I think this is breaking SASL.

I think this is caused by #179 which has upstream documentation issue https://github.com/kiwiirc/irc-framework/issues/106 which I think to be the cause.

**Comment by richrd** [comment]
This is because irc-framwork expects the `userName` to be passed as the `username` property in the config that's passed to `connect`. Currently it's not passed at all.

**Comment by Mikaela** [comment]
https://github.com/FruitieX/teleirc/pull/216 thanks for fixing SASL 💜 

`[SaslServ] T4!mikaela@PirateParty/FI/Bot has just authenticated as you (Euforia) `

**Comment by richrd** [comment]
You're welcome! Happy to contribute.
