### ISSUE TITLE
Add option to relay join part in tg group to IRC

### ISSUE THREAD

**Issue by acagastya** [FruitieX/teleirc#209]
It would be helpful to have information about who joined or left the telegram group on IRC chatrooms. Could you please add that feature?

**Comment by Mikaela** [comment]
Duplicate of https://github.com/FruitieX/teleirc/issues/193.

**Comment by acagastya** [comment]
@Mikaela this is different from #193. The bot should announce on IRC channel who joined the telegram group.

**Comment by Mikaela** [comment]
> The bot should announce on IRC channel who joined the telegram group.

I see `username was added by username`, but in that case this would be a duplicate of https://github.com/FruitieX/teleirc/issues/72 ?
