### ISSUE TITLE
How to send Botcommands?

### ISSUE THREAD

**Issue by dasTholo** [FruitieX/teleirc#21]
Hej, 
It is possible to send botcommand like "!bla" to send from Telegram to irc without "< Nick >"
relay all is true in config

**Comment by Bysmyyr** [comment]
hi, 

No, but in my opinion that can be easily implemented if there is a reason for that and somebody have motivation to do that.

**Comment by Omnimushu** [comment]
I'd like this implemented as well. I'd do it if I had the know how.

**Comment by FruitieX** [comment]
This could perhaps be implemented as a [module](https://github.com/FruitieX/teleirc/issues/29) in the future.

**Comment by martinie** [comment]
Doing this would be awesome, very awesome.

**Comment by FruitieX** [comment]
Will be fixed by #120.

Note that you must set config.allowCommands = true, as this can be dangerous in some cases (especially if the bot is opped) we default to not allowing commands.
