### ISSUE TITLE
config.ircOptions realName does nothing

### ISSUE THREAD

**Issue by Mikaela** [FruitieX/teleirc#212]
I think this is related to https://github.com/FruitieX/teleirc/issues/207 .

**Comment by richrd** [comment]
This is because irc-framwork expects the `realName` to be passed as `gecos` property in the config that's passed to `connect`. Currently it's not passed at all.

**Comment by richrd** [comment]
This is because irc-framwork expects the `realName` to be passed as `gecos` property in the config that's passed to `connect`. Currently it's not passed at all.
