### ISSUE TITLE
FiSH support

### ISSUE THREAD

**Issue by hlx98007** [FruitieX/teleirc#215]
I searched within the issue section and found no answer, will it be FiSH/blowfish support in the future?

Thanks.

**Comment by Mikaela** [comment]
I would say no as I haven't ever seen it used anywhere during my years of IRC usage and I consider server links being SSL enough.

I am not closing this yet in case @FruitieX considers this to be within the scope of TeleIRC.

**Comment by adedomin** [comment]
pretty sure FiSH is insecure, especially in this era. if you want support for some symmetric crypto it would be possible.... but why? it will be emitted in plaintext over telegram since group chats aren't encrypted using any exchange i know of.

**Comment by hlx98007** [comment]
@adedomin FiSH is a secure algorithm to date. I am trying to read off from an encrypted IRC channel to TG.

Problem is teleirc does not support network login capability, otherwise I would use ZNC to workaround the need & issue.

**Comment by Mikaela** [comment]
> Problem is teleirc does not support network login capability, otherwise I would use ZNC to workaround the need & issue.

What do you mean with network login capability? I am using TeleIRC with SASL without issues (which ZNC doesn't support though), but I think that it's possible to send server password without SASL too which would be what ZNC wants.

https://github.com/FruitieX/teleirc/blob/66817c017827f25867c238f14cb3cc10e27b55ad/src/config.defaults.js#L140-L162

**Comment by hlx98007** [comment]
@Mikaela This capability: https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands#PASS

**Comment by Mikaela** [comment]
@hlx98007 As far as I am aware that is what `password` under `config.ircOptions` does.

https://github.com/FruitieX/teleirc/blob/66817c017827f25867c238f14cb3cc10e27b55ad/src/config.defaults.js#L146

*See also my previous comment for more details.*

**Comment by hlx98007** [comment]
@Mikaela Thanks for the note, it looks like this is indeed passing PASS command to znc, the doc and example config did not include this and that was my bad for not reading the doc carefully.
