### ISSUE TITLE
executing /command telegram side causes double output

### ISSUE THREAD

**Issue by TomokoK** [FruitieX/teleirc#219]
When executing /command '_n_' telegram side, the bot will output **"Command '_n_' executed."** twice.
![Example](https://user-images.githubusercontent.com/13804161/32135962-371ef09e-bbd5-11e7-94ac-f09726d6b5e2.jpg)

**Comment by Mikaela** [comment]
Possibly related: https://github.com/FruitieX/teleirc/issues/137

**Comment by adedomin** [comment]
I can't reproduce this. is there some hidden step I'm not seeing?

**Comment by TomokoK** [comment]
No hidden steps at all, just execute /command telegram side and that happens.

**Comment by Mikaela** [comment]
I cannot reproduce this either. Which version of TeleIRC are you using?

> Version: teleirc git-226c7f8 (on branch: develop), npm-0.4.7

**Comment by TomokoK** [comment]
Current version: teleirc git-226c7f8 (on branch: develop), npm-0.4.7

**Comment by Mikaela** [comment]
Node version?

```
% node --version
v4.8.4
% npm --version
2.15.11
```

**Comment by TomokoK** [comment]
```
tomoko@znc:~$ node --version
v8.7.0
tomoko@znc:~$ npm --version
5.5.1
```

**Comment by TomokoK** [comment]
I removed the node_modules folder and reinstalled teleirc with npm install -g, and this bug seems to have gone away. I guess it was just an out of date module?
