### ISSUE TITLE
URL not forwared if send to Telegram app with "share" in android

### ISSUE THREAD

**Issue by petebp** [FruitieX/teleirc#223]
If you forward a link from an android phone, e.g. from Firefox to the Telegram App, teleirc will forward the caption, but not the original URL to IRC. In other word, the forwarded link is not send to IRC.

(affected version: 0.4.8 stable)

**Comment by Mikaela** [comment]
I wasn't able to reproduce.

**Comment by petebp** [comment]
I now figured out it's a specific behavior of #224 
If you set converting linebreaks to \n, forwarding links will not work.

**Comment by Mikaela** [comment]
I am closing this in favour of https://github.com/FruitieX/teleirc/issues/224 which I understood to be the actual issue.
