### ISSUE TITLE
Possibility to use chatid instead of title, or regexmatching of title

### ISSUE THREAD

**Issue by bdcuck** [FruitieX/teleirc#226]
Using the title is a really bad idea, I run into problems with forward slashes in titles.
Couldn't it be changed to a case insensitive regex match instead? Or even better, possibility to put the chatid in the config because that doesn't change a lot.

**Comment by bdcuck** [comment]
It turned out that the problem wasn't the slashes, but trying to join a channel with a password as parameter, while the channel doesn't have a password anymore. It just silently fails.

**Comment by Mikaela** [comment]
This would be a duplicate of https://github.com/FruitieX/teleirc/issues/94 in my opinion.
