### ISSUE TITLE
Images sent from Matrix don't appear

### ISSUE THREAD

**Issue by Varal7** [FruitieX/teleirc#234]
When a Matrix user is sending an image (IRC side), it is sent as an action, in this form:

<img width="850" alt="screen shot 2018-02-01 at 10 11 43 pm" src="https://user-images.githubusercontent.com/8019486/35714979-d178b63e-079d-11e8-8932-ee6102693550.png">

As you can see, the `*` becomes part of the link, which leads to 404 error when trying to click on it (TG side).

I suggest that we add a space before and after the `*` on Telegram side, so that images appear correctly.

<img width="901" alt="screen shot 2018-02-01 at 10 19 10 pm" src="https://user-images.githubusercontent.com/8019486/35715014-09814410-079e-11e8-9fc0-55536dc5c9be.png">

**Comment by Mikaela** [comment]
This was fixed in Matrix-appservice-irc four months ago https://github.com/matrix-org/matrix-appservice-irc/issues/406 but I guess fixing it here too doesn't hurt.

**Comment by Varal7** [comment]
Indeed, thanks!
