### ISSUE TITLE
Social card for this repo heads to 404 error

### ISSUE THREAD

**Issue by bunnybooboo** [FruitieX/teleirc#254]
Just spotted that the URL used in the description is replicated in shared social cards. That URL leads to a 404 error page. This example inside Slack:

![screenshot from 2018-05-22 13-43-23](https://user-images.githubusercontent.com/5793295/40363012-bffa7d68-5dbd-11e8-9a65-16100d5de827.png)

**Comment by FruitieX** [comment]
Oops, fixed!
