### ISSUE TITLE
Just show image url and don't serve the image

### ISSUE THREAD

**Issue by Thaodan** [FruitieX/teleirc#268]
Some have already a webserver running and don't want an external webserver.

**Comment by Mikaela** [comment]
Did you resolve this some other way or why did you close this?

Potentially related: https://github.com/FruitieX/teleirc/issues/256 https://github.com/FruitieX/teleirc/issues/262

**Comment by Thaodan** [comment]
Yes, I oversaw the option externalWebserver.
