### ISSUE TITLE
teleirc not relaying messages from other Telegram bots to IRC

### ISSUE THREAD

**Issue by CP1832** [FruitieX/teleirc#269]
Hi guys:

I wanted to let you know that my teleirc is working flawlessly sending messages from IRC to TG and viceversa, but it's not doing it so for other Telegram bots (which are on the same group than my teleirc) towards IRC. I enabled the debugging log level in config.js and even there I can't see this message from the IFTTT bot being received by teleirc. Attached are the logs and a screenshot of my Telegram group. As a side note, the timestampos on the logs are 4 hours ahead of the time shown on the Telegram group, just in case.

Please let me know if you need any further data.

Thanks in advance.

**Comment by CP1832** [comment]
For some reason, the files weren't uploaded, here's the image: https://i.imgur.com/c5Tg6wS.jpg and here's the logs: https://www93.zippyshare.com/v/gtqSjD1B/file.html

**Comment by Mikaela** [comment]
Telegram doesn't let bots see messages from other bots, so there is nothing that can be done to this.

> Why doesn't my bot see messages from other bots?
> 
> Bots talking to each other could potentially get stuck in unwelcome loops. To avoid this, we decided that bots will not be able to see messages from other bots regardless of mode.

* https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots
