### ISSUE TITLE
Please squash you commits to logical parts

### ISSUE THREAD

**Issue by Bysmyyr** [FruitieX/teleirc#27]
It is much more professional to push only fully working commits. So every stage in the sourcetree should work. That makes reading the history much easier and do not show your typos to everyone and give much more picture to companies when they like to hire you.

http://stackoverflow.com/questions/5721566/combining-multiple-commits-into-one-prior-to-push

**Comment by FruitieX** [comment]
:+1:

**Comment by Bysmyyr** [comment]
FruitieX: Please force this, that commit log is uqly to read. Also some commit messages would be nice.

**Comment by FruitieX** [comment]
You're right, I've been sloppy with this. Will be more careful in the future!

**Comment by FruitieX** [comment]
What's your opinion on merge commits also? Seems github makes these when accepting a pull request via the web interface. However now there also seems to be an option to squash pull requests into one commit message - that is of course not always what we want but a nice addition: https://github.com/blog/2141-squash-your-commits

**Comment by Bysmyyr** [comment]
I do not care about mergr commits. Those are easy to see and are easy to be skipped. With several ddevelopers with merge rights they are good way to see who was approver.

I think you can use that squashing when someone is not squashed it and it is one logical, otherwice you can ask dev to squash it manually.
