### ISSUE TITLE
IRC Perform

### ISSUE THREAD

**Issue by Omnimushu** [FruitieX/teleirc#28]
Is there a way to make it do a perform on connect to irc? So it can login to chanserv etc?

Also possible to give it irc commands such as op etc by typing a command? Adding simple irc scripts would be very useful

**Comment by Omnimushu** [comment]
Also possible to give it irc commands such as op etc by typing a command? Adding simple irc scripts would be very useful

**Comment by FruitieX** [comment]
IRC perform on connect should be quite simple to implement, and I think we should have this feature for the bot's own authentication purposes.

Implementation wise we can add an event listener for the [registered](https://node-irc.readthedocs.org/en/latest/API.html#'registered') event e.g. [here](https://github.com/FruitieX/teleirc/blob/develop/irc.js#L32), and make it send an IRC command of user's choice right away. I'll leave this task for a while if you want to give it a shot.

As for manually executable commands or scripts: I'm not sure if administrative tasks like this should be part of teleirc's scope, or IMHO at least not in core teleirc. We could eventually implement a loadable module system (similar to ZNC), and create a module for this functionality, so as to avoid feature creep in the core. I'll open a separate issue for the module feature, which can be part of a future release.

**Comment by Omnimushu** [comment]
Hi I don't suppose you have an update for this?

**Comment by FruitieX** [comment]
No, not yet. Busy weekend. :)

**Comment by FruitieX** [comment]
@Omnimushu if you'd like to test it out, do a checkout of the [`perform`](https://github.com/FruitieX/teleirc/tree/perform) branch. See the default config for an [example](https://github.com/FruitieX/teleirc/blob/perform/config.defaults.js#L43-L45).

**Comment by FruitieX** [comment]
Merged to develop.

**Comment by Omnimushu** [comment]
Hi there,

Updated the bot (finally) Perform doesn't appear to be working I'm afraid and the bot still keeps d'cing after about 6hours with EOF from client. I'm assured the server is fine by my hosting and to test I have been running an eggdrop too which stays online constantly. Any ideas?

Regards,

Date: Sun, 8 Nov 2015 02:12:47 -0800
