### ISSUE TITLE
Host Image files that were attached as "File"

### ISSUE THREAD

**Issue by fczuardi** [FruitieX/teleirc#46]
When the option to save images and host them on a webserver is set in the config file, teleirc interprets correctly and copy an image when it was sent by an user using the "Photo or Video" option, but not if the image was sent by the Telegram user as "File".

![screen shot 2016-02-19 at 9 42 09 am](https://cloud.githubusercontent.com/assets/7760/13174779/22ca8abe-d6ed-11e5-8418-6dd8fa52fe8e.png)

## Steps to reproduce

- on a Telegram group with a teleirc bot configured to host images, post an image using the option "Photo or Video"
- on that same group, post the same image using the option "File"

## Expected results

IRC users see links for both images

## Actual results

IRC users see the first link, but on the second one they see "(Document)"

**Comment by FruitieX** [comment]
Thanks for reporting. I'm guessing you're on the latest stable version from npm? I think this was fixed by pull request #43, so if you try running teleirc from the develop git branch this issue should be resolved. Hopefully we can release very soon on npm. I'm still waiting for a new version of the node-irc module, which will fix an annoying reconnect bug.

**Comment by fczuardi** [comment]
You are right, I am on 0.4.0, is there a way to install the develop version using npm? I tried:

```
npm install -g teleirc@develop
```

But it failed :(

**Comment by fczuardi** [comment]
hmm… I tried with ```npm install -g http://github.com/FruitieX/teleirc/tarball/develop``` and the build failed, something to do with node-icu-charset-detector

**Comment by FruitieX** [comment]
Hey, can you paste more of the error log here, and which distro are you running? In case of Debian/Ubuntu, does this help: `apt-get install libicu-dev`? If so I should add it to the README...

**Comment by FruitieX** [comment]
Welp, I'm also getting an error related to node-icu-charset-detector when installing dependencies for teleirc. However that's an optional dependency of the node-irc module, and the `npm install` command still finishes for me without errors - teleirc also works as expected. How annoying, will investigate...

**Comment by FruitieX** [comment]
Try adding the `--no-optional` flag to npm install arguments for now

**Comment by fczuardi** [comment]
apt-get said "libicu-dev is already the newest version", using ```--no-optional``` it installed :)

**Comment by FruitieX** [comment]
Good, if you got a chance to test the latest dev branch and think the functionality is sufficient there, please close this issue. Thanks! :)

**Comment by fczuardi** [comment]
ok, it's working

**Comment by FruitieX** [comment]
Ok thanks for confirming :+1:
