### ISSUE TITLE
Upgrading to a supergroup doesn't update chat_id file

### ISSUE THREAD

**Issue by lagleki** [FruitieX/teleirc#52]
After upgrading to supergroup teleirc can no longer send messages from IRC to Telegram.
The error is
```Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"[Error]: Bad Request: group chat is migrated to supergroup chat","parameters":{"migrate_to_chat_id":...```

"migrate_to_chat_id" has the necessary id. Teleirc should instead of outputting error use that id to write it to chat_id and resend failed messages (if any).

**Comment by lagleki** [comment]
nevermind. i just manually edited chat_id file to add new chat ids.

**Comment by lagleki** [comment]
Well, Telegram does return a notice that the group id has been changed and teels what is the new id. teleirc could use that information to update chat_id file automatically.

A low priority issue, I'd say.

**Comment by FruitieX** [comment]
Yes, thank you for reporting. I would not have realized that the id changes, will try to fix. So the new chat id is in that migrate_to_chat_id field?

**Comment by lagleki** [comment]
Yes. Updated the description of the issue.

**Comment by qvazzler** [comment]
@FruitieX any luck with this one? Another Repo with similar issues ([link to issue])(https://github.com/Flexget/Flexget/issues/967), would highly appreciate your findings.

**Comment by FruitieX** [comment]
I haven't had time to investigate this yet, but I'd imagine there's some sort of event fired when a group is upgraded to a supergroup. We can then handle this event and start using the new chat id.

**Comment by Mikaela** [comment]
The title is a little misleading as supergroups work the same way as normal group as long as the bot is invited after converting to supergroup.

**Comment by FruitieX** [comment]
@qvazzler I took a look, it seems when upgrading to a supergroup a `message` event is emitted with the `migrate_to_chat_id` set to the new chat_id. So the bot has to listen for this event and always check if this field is present, and in that case start using the new chatId. teleirc will handle this correctly in the next release.

**Comment by FruitieX** [comment]
This should be fixed now. Test it in the `045_rc` branch. If everything works, we'll release 0.4.5 by the end of next week!
