### ISSUE TITLE
can we show the original message in replyto messages?

### ISSUE THREAD

**Issue by lagleki** [FruitieX/teleirc#62]
in https://github.com/FruitieX/teleirc/commit/738ae5ed7352bb185be74baded611a9315763319#diff-a580c1ba0497b29ca59e113698fc745dR174 I can't see how to extract text of the message to which another participant replied.

**Comment by FruitieX** [comment]
The original message can be accessed via msg.reply_to_message.text.

However, how do we make this look good on the IRC side? Any ideas?

**Comment by Mikaela** [comment]
Traditional IRC replying has been:

```
2016-05-07 14:58:46+0300 <@Mikaela> mau ==> whatever I have to comment or something like this
```

But I guess something like

```
Mikaela: [This is the beginning of the message…] my answer
```

could possibly work and would also be consitent with Telegram as it also shows snippet of the original message in the beginning. 

I don't know if … can be used here as it's already used in line changes, but why not as it should be clear it's reply.

**Comment by Rat-S** [comment]
I agree with @Mikaela . We can show username and a small snippet. 
But it should be configurable by the person using the bot.

**Comment by richrd** [comment]
If the API has a way to get the message that the reply is related to, I could try to implement this. It's an issue I often have personally.

**Comment by FruitieX** [comment]
I believe the API does provide you with at least a handle to the original message

**Comment by richrd** [comment]
Should I try and go ahead with a PR for this?
I could go for the following implementation:
- Show original message in replies (snippet by default, configurable)
- Format the message in IRC the way @Mikaela suggested
- Option to change snippet length or show entire message (config variable, default ~ 150?)

Comments?

**Comment by FruitieX** [comment]
Sounds good! :-)

**Comment by richrd** [comment]
Been pretty busy this week, hopefully I'll bite into this on saturday.

**Comment by richrd** [comment]
Any objections to me just assigning `msg.reply_to_message` to `message.reply_to_message`? Maybe set it to null by default if no reply exists?

**Comment by richrd** [comment]
Here's my PR #182 let me know what you think!

**Comment by richrd** [comment]
@FruitieX @Mikaela @lagleki @Rat-S @adedomin & others, let me know your oppinion on this. Also what should we do when replying to pictures, documents, audio etc? Would be nice to get this polished and merged :)

**Comment by Mikaela** [comment]
Could the quote simply say `<filetype>`?

**Comment by richrd** [comment]
I'd agree with that. I think it'd be good to get this in with some basic solution and then improve it if users feel like it's not good enough.

**Comment by adedomin** [comment]
works for me

**Comment by richrd** [comment]
Thanks for the merge! There's still a small bug though, see this message: https://github.com/FruitieX/teleirc/pull/182#issuecomment-303115955

I think we should close this only after the bug is resolved.

**Comment by Mikaela** [comment]
Fixed by https://github.com/FruitieX/teleirc/pull/203 if I understood correctly.

@adedomin Could you check https://help.github.com/articles/closing-issues-using-keywords/ and use it in the future?
