### ISSUE TITLE
SASL support

### ISSUE THREAD

**Issue by lagleki** [FruitieX/teleirc#63]
Pardon for a noobish question but if I registered my bot with "username" and "password" on Freenode then what would be value of ircPerformCmds in the config file?

**Comment by Mikaela** [comment]
I would also be interested in how this happens especially by using SASL which has option in the config file but nothing to tell how to actually use it.

Currently I am not using SASL, but instead have this in the config file:

```
config.ircPerformCmds = ['NICKSERV identify username password'];
```

This works as `NICKSERV` is server side command which checks that `NickServ` is the real NickServ and not random user nicked to it (possible in case of server misconfiguration and has happened on probably all networks including freenode) and then sends the message to `NickServ` and is thus safer than `PRIVMSG NickServ :identify username password`.

However as this is not SASL, the bot joins channels before identifying and only identifies after joining which can be a issue. Also if freenode decided to require SASL from DigitalOcean IP ranges again, at least my instance would go down.

*SASL is a method to identifying to NickServ before even being visible to the network other than operators with snomask getting connection notices.*

**Comment by FruitieX** [comment]
Hi, yes SASL is undocumented and untested. It is simply a feature of node-irc, and the config parameters are passed directly to that module. According to [this](https://node-irc.readthedocs.org/en/latest/API.html), it should be sufficient to set the sasl parameter to true, and also nick, userName and password. If this works we could document this feature.

**Comment by Mikaela** [comment]
Where should the password be set?

**Comment by FruitieX** [comment]
Looks like it should be set in the [options object](https://github.com/martynsmith/node-irc/blob/3fde7c680a7578c8829ff117623f01f17155cee8/lib/irc.js#L610) passed to node-irc, so in our case inside `config.ircOptions = { ... }`

**Comment by FruitieX** [comment]
Did anyone get this working?

**Comment by Mikaela** [comment]
It seems I never commented here that when I set the password like instructed on 3rd of April, it simply got stuck as it didn't send AUTHENTICATE or did something else wrong on the IRCd side.

It also didn't timeout which it should do as otherwise when SASL is enabled and services are down, it will just be in reconnect loop instead of at IRC relaying messages.

**Comment by Mikaela** [comment]
PROTIP: `config.ircPerformCmds = ['NICKSERV identify USERNAME PASSWORD', 'NICKSERV regain BOTNICK'];`

* Identifies you to services (it would be nice if SASL did this, but AFAIK no one has gotten it to work).
* Disconnects the session usng BOTNICK and changes the bots nick to BOTNICK (this is nice especially if your users have scripts like WeeChats parse_relayed_msg so the bot doesn't most of time change its nick to something weird).

**Comment by Rat-S** [comment]
I am not sure of the technicality, but SASL just works fine. 

Freenode doesn't allow my bot to connect unless it is auth by SASL ( may be because my VPS' ip was blacklisted. )

So I had to use SASL and it worked smoothly. 
This is how the config looks with SASL:

`config.ircOptions = {`
    `userName: 'nick',`
    `nick: 'nick',`
    `password: 'password',`
    `sasl: true,`
    .
    .
`};`

**Comment by Mikaela** [comment]
Thanks @Rat-S, because you succeeded, I tried again and discovered from config file comment that I was missing `:` between `password` and the actual password, and I think it failed due to that.

The only difference to your config is that I didn't specify `nick: 'nick'` as it's specified elsewhere.

:+1: for closing now, but this should possibly be documented somewhere outside of this issue tracker.

**Comment by Mikaela** [comment]
So what is the situation with this?

**Comment by wxl** [comment]
Works for me. Would be super cool if we could get SASL EXTERNAL/CertFP working, but SASL PLAIN works fine.

**Comment by Mikaela** [comment]
I documented at https://github.com/FruitieX/teleirc/wiki/Identifying-to-NickServ so I am closing this. It's a wiki, so feel free to improve it if you see issues there :)
