### ISSUE TITLE
how to send formatted messages to Telegram?

### ISSUE THREAD

**Issue by lagleki** [FruitieX/teleirc#64]
Is rich text currently supported in any form? Which functions can enable it?
I mostly think of replacing ugly ```<username>``` imported from IRC with something prettier.

**Comment by lagleki** [comment]
The answer is to use in tg.js ```tg.sendMessage(channel.tgChatId, msg, {parse_mode: "Markdown"});``` or whatever format you want.

**Comment by FruitieX** [comment]
This would be neat as a parse as markdown config option, default can be on. Care to make a pull request? :)

**Comment by lagleki** [comment]
It appears that malformed markdown (like unclosed `_` tags) can lead to errors while trying to send a message to Telegram.

So I now recommend using escaping html entities and using `HTML` markdown instead.

**Comment by FruitieX** [comment]
Maybe we shouldn't support this as it can also be very confusing (and cause errors possibly as you say)

**Comment by FruitieX** [comment]
Alternatively there should be a command on the IRC side such as `!md parsed-markdown-here` which is required as a prefix for parsing the message as markdown

**Comment by lagleki** [comment]
2016-05-07 14:40 GMT+03:00 Rasmus Eskola <notifications@github.com>:

> Maybe we shouldn't support this as it can also be very confusing (and
> cause errors possibly as you say)
>

For markdown let's abandon it, yes.
For HTML it seems fine once you escape special symbols.

**Comment by FruitieX** [comment]
Think I'll close this then. Might do a markdown command at some point, as referenced from #29.

**Comment by lagleki** [comment]
What about HTML?

2016-05-07 15:00 GMT+03:00 Rasmus Eskola <notifications@github.com>:

**Comment by FruitieX** [comment]
We can have that as a separate command as well IMHO. I wouldn't necessarily want it to parse IRC messages as anything else than plain text by default.
