### ISSUE TITLE
Is there anyway to see who's on IRC

### ISSUE THREAD

**Issue by weiguxp** [FruitieX/teleirc#8]
Is there a method to retrieve a list of users that are currently in an IRC channel? say by manually typing in a command?

I'm currently using this for my active channel but i have i no idea if the user i'm talkign to us actually on IRC.

**Comment by FruitieX** [comment]
Not currently, but this should be very easy to implement. The `node-irc` module documentation says that you should be able to find the channel user list here: https://node-irc.readthedocs.org/en/latest/API.html#Client.chans, so it should be a matter of sending this list on request. If you or someone is interested in implementing this I will happily accept a pull request, I myself am a little bit busy with other things right now. :)
