### ISSUE TITLE
Command to add missing options to config file

### ISSUE THREAD

**Issue by Mikaela** [FruitieX/teleirc#91]
I think the config file has updated multiple times since I first installed TeleIRC, so I have old config files. It would be nice if there was `teleirc-updateconfig` which added the new configuration options and their defaults to my config file if they were missing, so I wouldn't have to discover those by myself.

Taking a backup of the current config might also be a good idea, `date -Is` would probably give reasonable file-extension to the backup.

**Comment by FruitieX** [comment]
Programmatically writing to the config file is a little bit troublesome, since it's just a JavaScript source file. Maybe we could just append missing lines to it though, and find & replace deprecated options with their new variants...

**Comment by FruitieX** [comment]
I sort of implemented this in https://github.com/FruitieX/teleirc/tree/updateConfig

I'm not entirely happy with it yet, as it does not insert e.g. comments above the new config options, and just does a crude find & replace on deprecated option names. Properly handling this probably involves changing the format of our config files, though.

**Comment by FruitieX** [comment]
Done for now. Opening a new issue about potentially changing our config file format.
